# SPDX-License-Identifier: Apache-2.0

# SPDX-FileCopyrightText: 2025 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
#
# This file is Free Software under the Apache-2.0 License
# without warranty, see README.md and LICENSES/Apache-2.0.txt for details.

languageCode = 'en-US'
title = 'CSAF'
disableKinds = ["taxonomy", "RSS", "sitemap"]
ignoreFiles = [".license$"]
canonifyURLs = "true"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      table = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
